const taxExemptionCodes = [
    // { code: 'M00', name: 'Transitional regime' },
    { code: 'M02', name: 'Transfer of goods and services not subject' },
    // { code: 'M04', name: 'VAT – Non-subjection regime' },
    { code: 'M10', name: 'Exempt under the terms of paragraph a) of nº1 of article 12 of the VAT Code' },
    { code: 'M11', name: 'Exempt under the terms of paragraph b) of nº1 of article 12 of the VAT Code' },
    { code: 'M12', name: 'Exempt under the terms of paragraph c) of nº1 of article 12 of the VAT Code' },
    { code: 'M13', name: 'Exempt under the terms of paragraph d) of nº1 of article 12 of the VAT Code' },
    { code: 'M14', name: 'Exempt under the terms of paragraph e) of nº1 of article 12 of the VAT Code' },
    { code: 'M15', name: 'Exempt under the terms of paragraph f) of nº1 of article 12 of the VAT Code' },
    { code: 'M16', name: 'Exempt under the terms of paragraph g) of nº1 of article 12 of the VAT Code' },
    { code: 'M17', name: 'Exempt under the terms of paragraph h) of nº1 of article 12 of the VAT Code' },
    { code: 'M18', name: 'Exempt under the terms of paragraph i) of nº1 of article 12 of the VAT Code' },
    { code: 'M19', name: 'Exempt under the terms of paragraph j) of nº1 of article 12 of the VAT Code' },
    { code: 'M20', name: 'Exempt under the terms of paragraph k) of nº1 of article 12 of the VAT Code' },
    { code: 'M21', name: 'Exempt under the terms of paragraph l) of nº1 of article 12 of the VAT Code' },
    { code: 'M22', name: 'Exempt under the terms of paragraph m) of article 12 of the VAT Code' },
    { code: 'M23', name: 'Exempt under the terms of paragraph n) of article 12 of the VAT Code' },
    { code: 'M24', name: 'Exempt under the terms of paragraph o) of article 12 of the VAT Code' },
    { code: 'M80', name: 'Exempt under the terms of paragraph a) of nº1 of article 14 of the VAT Code' },
    { code: 'M81', name: 'Exempt under the terms of paragraph b) of nº1 of article 14 of the VAT Code' },
    { code: 'M82', name: 'Exempt under the terms of paragraph c) of nº1 of article 14 of the VAT Code' },
    { code: 'M83', name: 'Exempt under the terms of paragraph d) of nº1 of article 14 of the VAT Code' },
    { code: 'M84', name: 'Exempt under the terms of paragraph e) of nº1 of article 14 of the VAT Code' },
    { code: 'M85', name: 'Exempt under the terms of paragraph a) of nº2 of article 14 of the VAT Code' },
    { code: 'M86', name: 'Exempt under the terms of paragraph b) of nº2 of article 14 of the VAT Code' },
    { code: 'M30', name: 'Exempt under the terms of paragraph a) of article 15 of the VAT Code' },
    { code: 'M31', name: 'Exempt under the terms of paragraph b) of article 15 of the VAT Code' },
    { code: 'M32', name: 'Exempt under the terms of paragraph c) of article 15 of the VAT Code' },
    { code: 'M33', name: 'Exempt under the terms of paragraph d) of article 15 of the VAT Code' },
    { code: 'M34', name: 'Exempt under the terms of paragraph e) of article 15 of the VAT Code' },
    { code: 'M35', name: 'Exempt under the terms of paragraph f) of article 15 of the VAT Code' },
    { code: 'M36', name: 'Exempt under the terms of paragraph g) of article 15 of the VAT Code' },
    { code: 'M37', name: 'Exempt under the terms of paragraph h) of article 15 of the VAT Code' },
    { code: 'M38', name: 'Exempt under the terms of paragraph i) of article 15 of the VAT Code' },
    { code: 'M90', name: 'Exempt under the terms of paragraph a) of nº1 of article 16 of the VAT Code' },
    { code: 'M91', name: 'Exempt under the terms of paragraph b) of nº1 of article 16 of the VAT Code' },
    { code: 'M92', name: 'Exempt under the terms of paragraph c) of nº1 of article 16 of the VAT Code' },
    { code: 'M93', name: 'Exempt under the terms of paragraph d) of nº1 of article 16 of the VAT Code' },
    { code: 'M94', name: 'Exempt under the terms of paragraph e) of nº1 of article 16 of the VAT Code' }
];

const taxExemption = [
    // { code: 'M00', name: 'Regime transitório' },
    { code: 'M02', name: 'Transmissão de bens e serviço não sujeita' },
    // { code: 'M04', name: `IVA – Regime de não sujeição` },
    { code: 'M10', name: 'Isento nos termos da alínea a) do nº1 do artigo 12.º do CIVA' },
    { code: 'M11', name: 'Isento nos termos da alínea b) do nº1 do artigo 12.º do CIVA' },
    { code: 'M12', name: 'Isento nos termos da alínea c) do nº1 do artigo 12.º do CIVA' },
    { code: 'M13', name: 'Isento nos termos da alínea d) do nº1 do artigo 12.º do CIVA' },
    { code: 'M14', name: 'Isento nos termos da alínea e) do nº1 do artigo 12.º do CIVA' },
    { code: 'M15', name: 'Isento nos termos da alínea f) do nº1 do artigo 12.º do CIVA' },
    { code: 'M16', name: 'Isento nos termos da alínea g) do nº1 do artigo 12.º do CIVA' },
    { code: 'M17', name: 'Isento nos termos da alínea h) do nº1 do artigo 12.º do CIVA' },
    { code: 'M18', name: 'Isento nos termos da alínea i) do nº1 artigo 12.º do CIVA' },
    { code: 'M19', name: 'Isento nos termos da alínea j) do nº1 do artigo 12.º do CIVA' },
    { code: 'M20', name: 'Isento nos termos da alínea k) do nº1 do artigo 12.º do CIVA' },
    { code: 'M21', name: 'Isento nos termos da alínea l) do nº1 do artigo 12.º do CIVA' },
    { code: 'M22', name: 'Isento nos termos da alínea m) do artigo 12.º do CIVA' },
    { code: 'M23', name: 'Isento nos termos da alínea n) do artigo 12.º do CIVA' },
    { code: 'M24', name: 'Isento nos termos da alínea 0) do artigo 12.º do CIVA' },
    { code: 'M80', name: 'Isento nos termos da alínea a) do nº1 do artigo 14.º do CIVA' },
    { code: 'M81', name: 'Isento nos termos da alínea b) do nº1 do artigo 14.º do CIVA' },
    { code: 'M82', name: 'Isento nos termos da alínea c) do nº1 do artigo 14.º do CIVA' },
    { code: 'M83', name: 'Isento nos termos da alínea d) do nº1 do artigo 14.º do CIVA' },
    { code: 'M84', name: 'Isento nos termos da alínea e) do nº1 do artigo 14.º do CIVA' },
    { code: 'M85', name: 'Isento nos termos da alínea a) do nº2 do artigo 14.º do CIVA' },
    { code: 'M86', name: 'Isento nos termos da alínea b) do nº2 do artigo 14.º do CIVA' },
    { code: 'M30', name: 'Isento nos termos da alínea a) do artigo 15.º do CIVA' },
    { code: 'M31', name: 'Isento nos termos da alínea b) do artigo 15.º do CIVA' },
    { code: 'M32', name: 'Isento nos termos da alínea c) do artigo 15.º do CIVA' },
    { code: 'M33', name: 'Isento nos termos da alínea d) do artigo 15.º do CIVA' },
    { code: 'M34', name: 'Isento nos termos da alínea e) do artigo 15.º do CIVA' },
    { code: 'M35', name: 'Isento nos termos da alínea f) do artigo 15.º do CIVA' },
    { code: 'M36', name: 'Isento nos termos da alínea g) do artigo 15.º do CIVA' },
    { code: 'M37', name: 'Isento nos termos da alínea h) do artigo 15.º do CIVA' },
    { code: 'M38', name: 'Isento nos termos da alínea i) do artigo 15.º do CIVA' },
    { code: 'M90', name: 'Isento nos termos da alínea a) do nº1 do artigo 16.º do CIVA' },
    { code: 'M91', name: 'Isento nos termos da alínea b) do nº1 do artigo 16.º do CIVA' },
    { code: 'M92', name: 'Isento nos termos da alínea c) do nº1 do artigo 16.º do CIVA' },
    { code: 'M93', name: 'Isento nos termos da alínea d) do nº1 do artigo 16.º do CIVA' },
    { code: 'M94', name: 'Isento nos termos da alínea e) do nº1 do artigo 16.º do CIVA' }
];
  
export default taxExemptionCodes;
  